# Generated by Django 4.2.18 on 2025-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomponent',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
