# Generated by Django 4.2.18 on 2025-02-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_task_setting_1_task_setting_2_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
