# Generated by Django 4.2.18 on 2025-02-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_rename_author_tools_author_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='setting_1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='setting_2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='setting_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='setting_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskcomponent',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
