# Generated by Django 4.2.18 on 2025-02-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_remove_task_setting_1_remove_task_setting_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomponent',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
