# Generated by Django 4.2.18 on 2025-02-15 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_taskcomponent_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='program',
        ),
    ]
