# Generated by Django 4.2.18 on 2025-02-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0007_remove_task_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='product',
        ),
    ]
