# Generated by Django 4.2.18 on 2025-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0008_remove_task_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
