# Generated by Django 4.2.18 on 2025-02-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0010_product_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomponent',
            name='end_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_product', to='dog.product'),
        ),
        migrations.AlterField(
            model_name='taskcomponent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='dog.product'),
        ),
    ]
