# Generated by Django 4.2.18 on 2025-03-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0011_taskcomponent_end_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndProductUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.product')),
                ('task_list_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.tasklistmatch')),
                ('used_in_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.task')),
            ],
        ),
    ]
