# Generated by Django 4.2.18 on 2025-03-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0012_endproductuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproductuse',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.tasklist'),
        ),
    ]
