# Generated by Django 4.2.18 on 2025-03-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0013_endproductuse_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endproductuse',
            name='task_list_match',
        ),
    ]
