# Generated by Django 4.2.18 on 2025-03-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0014_remove_endproductuse_task_list_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndProductUse',
            new_name='EndProductUsage',
        ),
    ]
