# Generated by Django 4.2.18 on 2025-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0015_rename_endproductuse_endproductusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproductusage',
            name='felix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
