# Generated by Django 4.2.18 on 2025-03-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0016_endproductusage_felix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endproductusage',
            name='end_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ep_product', to='dog.product'),
        ),
        migrations.AlterField(
            model_name='endproductusage',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ep_tasklist', to='dog.tasklist'),
        ),
        migrations.AlterField(
            model_name='endproductusage',
            name='used_in_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ep_task', to='dog.task'),
        ),
    ]
