# Generated by Django 4.2.18 on 2025-03-12 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0017_alter_endproductusage_end_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproductusage',
            name='added_from_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.task'),
        ),
    ]
