# Generated by Django 4.2.18 on 2025-03-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0018_endproductusage_added_from_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproductusage',
            name='task_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.taskcomponent'),
        ),
    ]
