# Generated by Django 4.2.18 on 2025-03-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0019_endproductusage_task_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='endproductusage',
            name='task_list_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ep_tasklist', to='dog.tasklistmatch'),
        ),
    ]
