# Generated by Django 4.2.18 on 2025-03-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0021_toolcategory_toolcategorymatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcategorymatch',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='toolcategorymatch',
            name='tool_id',
        ),
        migrations.DeleteModel(
            name='ToolCategory',
        ),
        migrations.DeleteModel(
            name='ToolCategoryMatch',
        ),
    ]
