# Generated by Django 4.2.18 on 2025-03-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0023_toolcategory_toolcategorymatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_result', models.CharField(blank=True, max_length=255, null=True)),
                ('task_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.toolcategory')),
            ],
        ),
        migrations.RenameField(
            model_name='toolcategorymatch',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='toolcategorymatch',
            old_name='tool_id',
            new_name='tool',
        ),
        migrations.CreateModel(
            name='UsedForMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.tools')),
                ('used_for_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.usedfor')),
            ],
        ),
    ]
