# Generated by Django 4.2.18 on 2025-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0024_usedfor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
