# Generated by Django 4.2.18 on 2025-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0025_toolcategory_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'ordering': ['name'], 'verbose_name': 'Tool Category', 'verbose_name_plural': 'Tool Categories'},
        ),
    ]
