# Generated by Django 4.2.18 on 2025-04-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0026_alter_toolcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={},
        ),
    ]
