# Generated by Django 4.2.18 on 2025-04-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0027_alter_toolcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dog.toolcategory'),
        ),
    ]
