# Generated by Django 4.2.18 on 2025-04-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0028_alter_toolcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dog.toolcategory', verbose_name='Parent Category'),
        ),
    ]
