# Generated by Django 4.2.18 on 2025-04-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0029_alter_toolcategory_name_alter_toolcategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.AlterField(
            model_name='toolcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dog.toolcategory'),
        ),
    ]
