# Generated by Django 4.2.18 on 2025-04-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0030_alter_toolcategory_options_alter_toolcategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={},
        ),
    ]
