# Generated by Django 4.2.18 on 2025-04-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0031_alter_toolcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name_plural': 'Tool Categories'},
        ),
    ]
