# Generated by Django 4.2.18 on 2025-04-19 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0032_alter_toolcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={},
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.toolcategory'),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='tool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dog.tools'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcategorymatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tools',
            name='categories',
            field=models.ManyToManyField(through='dog.ToolCategoryMatch', to='dog.toolcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='toolcategory',
            unique_together={('tool', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='toolcategorymatch',
            unique_together={('tool', 'category')},
        ),
        migrations.RemoveField(
            model_name='toolcategory',
            name='temp',
        ),
    ]
