# Generated by Django 4.2.18 on 2025-04-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0033_alter_toolcategory_options_toolcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolcategory',
            options={'verbose_name_plural': 'Tool Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='toolcategory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='toolcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='toolcategory',
            name='tool',
        ),
    ]
